# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Permalinks
permalink:          /blogs/:categories/:title:output_ext

# Site settings
title:
  en:               Ubisen
  vi:               Ubisen

name: Ubisen
description:
  en:               An Internet of Things platform and technology company. Trends of supervising and control devices via the Internet (Internet of Things - IOT) are becoming increasingly popular , with Enterprise Service Integration M2M platform , Ubisen platform is the solution which helps businesses save time to build , deploy secure IOT system.
  vi:               Giải pháp IOT kết nối tất cả thiết bị qua Internet. Xu hướng kết nối giám sát điều khiển thiết bị qua internet ( Internet of Things- IOT) đang ngày càng phổ biến, với nền tảng M2M Enterprise Service Integration, Ubisen platform là giải pháp giúp doanh nghiệp tiết kiệm thời gian xây dựng, triển khai hệ thống IOT an toàn, bảo mật.

index:
  en:
  vi:               vi

language:
  en:               English
  vi:               Tiếng Việt

flag:
  en: /images/en.png
  vi: /images/vi.png

url:                 https://ubisen.com
baseurl:             ""

paginate:            1
paginate_path:       /blogs/page:num

author:
  name:              Ubisen
  url:               https://ubisen.com
  email:             contacts@ubisen.com


collections:
  solutions:
    output: true
  products:
    output: true

# Custom vars
version:             0.0.1

# Build settings
markdown:            kramdown

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
